language: node_js
node_js:
  - 10
os: linux
# Only build for tags, not for untagged commits
# see https://github.com/travis-ci/travis-ci/issues/6893#issuecomment-354967391
if: tag IS present
cache: yarn
# Handle git submodules yourself
# see https://stackoverflow.com/a/24600210
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
# see https://stackoverflow.com/a/24600210
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - npm config set spin false
  - npm install --global yarn
install:
  - yarn install
script:
  - yarn build
before_deploy:
  # see https://superuser.com/a/496903
  - zip -r /tmp/dfh-wordpress-theme-${TRAVIS_TAG}.zip . -x 'node_modules/*' 'src/*' '.git*' '*.log' '*.DS_Store*' '*.sublime*'
deploy:
  - provider: releases
    token: ${GITHUB_TOKEN}
    file: /tmp/dfh-wordpress-theme-${TRAVIS_TAG}.zip
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
